name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  checkout:
    name: Checkout do código
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

  build:
    name: Build do projeto
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "22"

      - name: Build com Maven
        run: mvn clean install

  lint-test:
    uses: ./.github/workflows/lint-and-test.yml
    needs: build
    with:
      java_version: "22"

  package:
    name: Gerar JAR
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "22"

      - name: Empacotar JAR
        run: mvn package

  deploy:
    name: Deploy simbólico
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Mensagem de deploy
        run: echo "Deploy realizado com sucesso"
