name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - "src/**"

jobs:
  checkout:
    name: Checkout do c贸digo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do reposit贸rio
        uses: actions/checkout@v4

  build:
    name: Build do projeto
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout do reposit贸rio
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "22"

      - name: Build com Maven
        run: mvn clean install

  test:
    name: Executar testes
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do reposit贸rio
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "22"

      - name: Executar testes
        run: mvn test
