name: Check Deploy Status

on:
  workflow_dispatch:

jobs:
  check-deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_STATUS: ""

    steps:
      - name: Verificar status de deploy
        run: |
          echo "Status recebido: '$DEPLOY_STATUS'"
          if [ -z "$DEPLOY_STATUS" ] || [ "$DEPLOY_STATUS" != "success" ]; then
            echo "Deploy falhou, chamando fluxo de criação de issue."
            echo "trigger_issue=true" >> "$GITHUB_ENV"
          else
            echo "Deploy realizado com sucesso."
            echo "trigger_issue=false" >> "$GITHUB_ENV"

  call-create-issue:
    needs: check-deploy
    if: ${{ env.trigger_issue == 'true' }}
    uses: ./.github/workflows/create-issue.yml
    secrets:
      ISSUE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
