name: Hello Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensagem
        run: echo "Pipeline iniciado com sucesso"
