name: Using vars & secrets

on:
  workflow_dispatch:

jobs:
  using-vars-secrets:
    runs-on: ubuntu-latest
    env:
      STAGE: development

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Exibir variáveis de nível repositório
        run: |
          echo "APP_MODE = ${{ vars.APP_MODE }}"
          echo "SUPPORT_EMAIL = ${{ vars.SUPPORT_EMAIL }}"
          echo "STAGE (env) = $STAGE"

      - name: Simulando autenticação por token
        run: |
          echo "Autenticando..."
          if [ -z "${{ secrets.PROD_TOKEN }}" ]; then
            echo "O token PROD_TOKEN está ausente impossível autenticar!"
            exit 1
          fi
          echo "Autenticação realizada com sucesso pelo token PROD_TOKEN!"
